# Generated by Django 3.0.6 on 2020-06-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Modified at')),
                ('accessed', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('slug', models.CharField(default='', max_length=128)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='en', max_length=2)),
                ('visible', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=True)),
                ('static', models.BooleanField(default=False)),
                ('extended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('accessed_at', models.DateTimeField(auto_now=True, verbose_name='Accessed at')),
                ('accessed', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('filesize', models.IntegerField(default=0)),
                ('filetype', models.CharField(max_length=4, null=True)),
                ('identifier', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('extended', models.BooleanField(default=False)),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.File')),
            ],
        ),
    ]
