# Generated by Django 3.0.6 on 2020-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='post',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='post',
            new_name='data',
        ),
    ]
