# Generated by Django 3.0.6 on 2020-05-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20200521_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.Chapter'),
        ),
    ]
