# Generated by Django 3.0.6 on 2020-05-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=256)),
                ('feed', models.URLField(max_length=256)),
                ('retrieved_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='US', max_length=2)),
                ('timezone', models.CharField(default='US', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('description', models.TextField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.NewsSource')),
            ],
        ),
    ]
